#!/bin/sh
LIBS=/opt/ninthdrug/scriptcache
for JAR in /opt/ninthdrug/lib/*.jar
do
  LIBS=$LIBS:$JAR
done
echo $LIBS
exec $SCALA_HOME/bin/scala -cp $LIBS "$0" "$@"
!#

import ninthdrug.http._

val server = new WebServer(
  ServerConfig(
    "/opt/ninthdrug/scriptcache",
    List(
      SiteConfig("www.kalrsn.com", "", 8080, "", "/opt/ninthdrug/websites/taakapp")
    )
  )
)

server.run()
